In [1]:
import numpy as np

a = np.arange(2*3*5*5).reshape((2, 3, 5, 5)) #2*3*3*3

print(a)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]
   [ 20  21  22  23  24]]

  [[ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]
   [ 40  41  42  43  44]
   [ 45  46  47  48  49]]

  [[ 50  51  52  53  54]
   [ 55  56  57  58  59]
   [ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]]]


 [[[ 75  76  77  78  79]
   [ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]
   [120 121 122 123 124]]

  [[125 126 127 128 129]
   [130 131 132 133 134]
   [135 136 137 138 139]
   [140 141 142 143 144]
   [145 146 147 148 149]]]]


In [2]:
b = np.ones((3, 5, 5, 8))
print(b)

[[[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
c = np.tensordot(a, b, axes=3).reshape(2, 8, 1, 1)
print(c.shape)
print(c, c.shape)

(2, 8, 1, 1)
[[[[2775.]]

  [[2775.]]

  [[2775.]]

  [[2775.]]

  [[2775.]]

  [[2775.]]

  [[2775.]]

  [[2775.]]]


 [[[8400.]]

  [[8400.]]

  [[8400.]]

  [[8400.]]

  [[8400.]]

  [[8400.]]

  [[8400.]]

  [[8400.]]]] (2, 8, 1, 1)


In [4]:
x1 = np.ones((3, 3, 3))
p1 = np.zeros((3, 1, 3))
p2 = np.zeros((3, 5, 1))
x1 = np.concatenate((p1, x1, p1), axis=1)
print(x1.shape)
x1 = np.concatenate((p2, x1, p2), axis=2)
print(x1)

(3, 5, 3)
[[[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]]


In [5]:
np.random.seed(10)
window = np.arange(2*3*2*2).reshape(2, 3, 2, 2)
window = np.random.randint(0, 10, size=(2, 3, 2, 2))
max_val = np.max(window, axis=(2, 3))
out = np.zeros((2, 3, 1, 1))
out[:, :, 0, 0] = max_val
print(out)
#print(window)
print(max_val, max_val.shape)
window_r = window.reshape(2, 3, 4)
#print(window)
max_index = np.argmax(window_r, axis=2)#.reshape(2, 3, 1, 1, 2)
max_w = max_index // 2
max_h = max_index % 2
max_pos = np.stack((max_w, max_h), axis=-1).reshape(2, 3, 2)
print(max_pos, max_pos.shape)
print(window[1, 1, 0,1])

[[[[9.]]

  [[9.]]

  [[9.]]]


 [[[4.]]

  [[8.]]

  [[6.]]]]
[[9 9 9]
 [4 8 6]] (2, 3)
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 1]
  [1 1]]] (2, 3, 2)
8


In [18]:
x = np.zeros((10, 8, 3))
w = np.zeros((9, 8))
print((w @ x).shape)

(10, 9, 3)
